# Generated by Django 3.2.8 on 2022-11-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(max_length=80)),
                ('price_1', models.FloatField()),
                ('price_2', models.FloatField()),
                ('price_3', models.FloatField()),
                ('price_4', models.FloatField()),
                ('download', models.BooleanField(default=False)),
            ],
        ),
    ]
