# Generated by Django 3.2.8 on 2022-11-17 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='code',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
